export const NONE = 'NONE';
export const ROOM = 'ROOM';
export const CHAT_MESSAGE = 'CHAT_MESSAGE';
export const CHAT_PARTICIPANTS = 'CHAT_PARTICIPANTS';
export const CHAT_PRIORITY_NOTIFICATION = 'CHAT_PRIORITY_NOTIFICATION';
export const CHECKLIST_ITEM = 'CHECKLIST_ITEM';
export const CHECKLIST_ITEM_COMMENT = 'CHECKLIST_ITEM_COMMENT';
